add coding style rule github action #60

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,7 +8,41 @@ on:
       - "ga-ignore-*"
 
 jobs:
+  check_coding_style:
+    runs-on: ubuntu-latest
+    container:
+      image: ghcr.io/epitech/coding-style-checker:latest
+    steps:
+      - name: checkout current repo
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: execute coding style . .
+        run: |
+          check.sh $(pwd) $(pwd)
+      - name: print error annotations
+        timeout-minutes: 2
+        run: |
+            if [ -s "coding-style-reports.log" ]; then
+              errors_found=false
+              while IFS= read -r line; do
+                if [[ "$line" != "" ]]; then
+                  error_type=$(echo "$line" | awk -F '[-: ]+' '{print $3}')
+                  filename=$(echo "$line" | cut -d ':' -f 1)
+                  line_number=$(echo "$line" | cut -d ':' -f 2)
+                  error_code=$(echo "$line" | cut -d '-' -f 2)
+                  title="$error_type coding style error: #$filename##L$line_number"
+                  description="C-$error_code"
+                  echo "::error title=\"$title\":: $description"
+                  errors_found=true
+                fi
+              if [[ "$errors_found" == true ]]; then
+                exit 1
+              fi
+            fi
   check_compilation:
+    needs:
+      - check_coding_style
     runs-on: ubuntu-latest
     container:
       image: epitechcontent/epitest-docker:latest
